### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (50,) (200,)

### ISSUE THREAD

**Issue by Vimim3** [fancompute/legume#47] opened 2022-12-24 12:27 UTC
when I use the following command to plot the field profile, I find I can only successfully plot the field when N1=N2, otherwise it will return an error.

"legume.viz.field(gme, 'e', 0, 0, z=D1/2, component='x', val='abs', N1=50, N2=100, cbar=True, eps=True)"

The detailed information about the error is "ValueError: operands could not be broadcast together with shapes (50,) (200,) "

How to solve this problem?

**Comment by momchil-flex** [comment] 2022-12-24 20:29
I cannot reproduce. For starters please always show the full stack trace rather than the final error only. But even then I may need a full script that reproduces the error, since I tried plotting something arbitrary with N1 != N2 and it worked.

**Comment by Vimim3** [comment] 2022-12-26 01:47
Thank you for your kind remind. The full information about this error is below:

Traceback (most recent call last):
  File "F:\Anaconda3-5.2.0install\lib\site-packages\IPython\core\interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-22-9875ea209407>", line 8, in <module>
    ax1 = legume.viz.field(gme, 'h', kind1, mind1, z=D1/2, periodic=False, component='z', val='re', N1=N11, N2=N21, cbar=True, eps=True)
  File "F:\Anaconda3-5.2.0install\lib\site-packages\legume\viz.py", line 727, in field
    1j*grid2*struct.kpoints[1, kind])
ValueError: operands could not be broadcast together with shapes (50,) (100,)

The attached file is the script and associated data file. Thank you very much!
[edge state.zip](https://github.com/fancompute/legume/files/10301049/edge.state.zip)

**Comment by momchil-flex** [comment] 2023-01-31 23:31
Hi. Sorry this took me a while, but also I still cannot reproduce. Your script requires some of your local files to run (see load_path1 and load_path2).

**Comment by Vimim3** [comment] 2023-02-02 07:44
I am sorry about this. I forgot to remind you that the required local files are xyR1.mat and xyR2.mat. They are included in the attached file. If you can not find them, please let me know.

**Comment by momchil-flex** [comment] 2023-02-02 18:50
Ah, sorry, I should have been able to figure that out! I can reproduce now, hopefully it will be a quick fix, but again I just need to find some time...

**Comment by momchil-flex** [comment] 2023-02-05 20:09
Should be fixed in newly released 0.1.10

**Closed by momchil-flex** 2023-02-05 20:09 UTC

**Comment by Vimim3** [comment] 2023-02-06 00:56
Thank you very much!
